call npm link cadmus-admin
call npm link cadmus-api
call npm link cadmus-core
call npm link cadmus-item-editor
call npm link cadmus-item-list
call npm link cadmus-item-search
call npm link cadmus-login
call npm link cadmus-material
call npm link cadmus-part-general-pg
call npm link cadmus-part-general-ui
call npm link cadmus-part-philology-pg
call npm link cadmus-part-philology-ui
call npm link cadmus-reset-password
call npm link cadmus-state
call npm link cadmus-thesaurus-editor
call npm link cadmus-thesaurus-list
call npm link cadmus-ui
call npm link cadmus-ui-pg
call npm link cadmus-user
pause
